spring:
#  session:
#    store-type: redis
#  redis:
#    host: localhost
#    port: 6379
  security:
    user:
      name: fox
      password: 123456
      roles: ADMIN
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springsecurity_demo_database?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
server:
  servlet:
    session:
      timeout: 600s
  port: 8080

